  #!/bin/bash
 
 # hicExplorer v3.7.1
 
hicCompareMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.norm.KR.h5 resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.KR.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrixDiff/I158A-old_vs_N2-old.bwa_mem.25kb.norm.KR.h5 --operation ratio --noNorm
hicCompareMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.norm.KR.h5 resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.KR.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrixDiff/hpl2-old_vs_N2-old.bwa_mem.25kb.norm.KR.h5 --operation ratio --noNorm
hicCompareMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.norm.KR.h5 resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.KR.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrixDiff/hpl2-lin61-old_vs_N2-old.bwa_mem.25kb.norm.KR.h5 --operation ratio --noNorm
hicCompareMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/CEC4_merged.bwa_mem.25kb.norm.KR.h5 resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.KR.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrixDiff/CEC4_vs_N2-old.bwa_mem.25kb.norm.KR.h5 --operation ratio --noNorm
hicCompareMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.norm.KR.h5 resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.KR.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrixDiff/lin61-old_vs_N2-old.bwa_mem.25kb.norm.KR.h5 --operation ratio --noNorm
hicCompareMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.norm.KR.h5 resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.KR.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrixDiff/met2-set25-set32-old_vs_N2-old.bwa_mem.25kb.norm.KR.h5 --operation ratio --noNorm
