(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/lin61-old_rep1_R1.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/lin61-old_rep1_1.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/lin61-old_rep1_1.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/lin61-old_rep1_R2.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/lin61-old_rep1_2.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/lin61-old_rep1_2.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/hpl2-lin61-old_rep1_R1.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep1_1.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep1_1.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/N2-old_rep1_R1.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/N2-old_rep1_1.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/N2-old_rep1_1.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/hpl2-lin61-old_rep1_R2.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep1_2.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep1_2.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/N2-old_rep1_R2.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/N2-old_rep1_2.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/N2-old_rep1_2.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/hpl2-lin61-old_rep2_R1.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep2_1.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep2_1.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/hpl2-lin61-old_rep2_R2.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep2_2.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep2_2.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/met2-set25-set32-old_rep1_R1.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/met2-set25-set32-old_rep1_1.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/met2-set25-set32-old_rep1_1.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/met2-set25-set32-old_rep1_R2.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/met2-set25-set32-old_rep1_2.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/met2-set25-set32-old_rep1_2.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/hpl2-old_rep1_R1.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/hpl2-old_rep1_1.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/hpl2-old_rep1_1.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/hpl2-old_rep1_R2.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/hpl2-old_rep1_2.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/hpl2-old_rep1_2.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/I158A-old_rep1_R1.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/I158A-old_rep1_1.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/I158A-old_rep1_1.bwa_mem.log 2>&1
(bwa mem -t 1  /nfs/work/gen2i/technique/bdd/bioDB/ce11/genome/Caenorhabditis_elegans.WBcel235.dna_sm.toplevel.fa resources/raw_data/NGS/HiC/I158A-old_rep1_R2.fq.gz | samtools view -Sbh -o resources/processed_data/ce11/NGS/HiC/bam/I158A-old_rep1_2.bwa_mem.bam) >resources/processed_data/ce11/NGS/HiC/bam/I158A-old_rep1_2.bwa_mem.log 2>&1
hicBuildMatrix --inputBufferSize 200000 --restrictionSequence GATC --restrictionCutFile resources/processed_data/ce11/genomics/bed/hicFindRestSite/GATC.bed --danglingSequence GATC --maxLibraryInsertSize 700 --samFiles resources/processed_data/ce11/NGS/HiC/bam/hpl2-old_rep1_1.bwa_mem.bam resources/processed_data/ce11/NGS/HiC/bam/hpl2-old_rep1_2.bwa_mem.bam --binSize 1000 --minMappingQuality 20 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_rep1.bwa_mem.1kb.h5 --QCfolder resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_rep1.bwa_mem.1kb_QC --threads 1 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_rep1.bwa_mem1kb.hicBuildMatrix.log
hicBuildMatrix --inputBufferSize 200000 --restrictionSequence GATC --restrictionCutFile resources/processed_data/ce11/genomics/bed/hicFindRestSite/GATC.bed --danglingSequence GATC --maxLibraryInsertSize 700 --samFiles resources/processed_data/ce11/NGS/HiC/bam/lin61-old_rep1_1.bwa_mem.bam resources/processed_data/ce11/NGS/HiC/bam/lin61-old_rep1_2.bwa_mem.bam --binSize 1000 --minMappingQuality 20 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_rep1.bwa_mem.1kb.h5 --QCfolder resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_rep1.bwa_mem.1kb_QC --threads 1 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_rep1.bwa_mem1kb.hicBuildMatrix.log
hicBuildMatrix --inputBufferSize 200000 --restrictionSequence GATC --restrictionCutFile resources/processed_data/ce11/genomics/bed/hicFindRestSite/GATC.bed --danglingSequence GATC --maxLibraryInsertSize 700 --samFiles resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep1_1.bwa_mem.bam resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep1_2.bwa_mem.bam --binSize 1000 --minMappingQuality 20 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_rep1.bwa_mem.1kb.h5 --QCfolder resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_rep1.bwa_mem.1kb_QC --threads 1 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_rep1.bwa_mem1kb.hicBuildMatrix.log
hicBuildMatrix --inputBufferSize 200000 --restrictionSequence GATC --restrictionCutFile resources/processed_data/ce11/genomics/bed/hicFindRestSite/GATC.bed --danglingSequence GATC --maxLibraryInsertSize 700 --samFiles resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep2_1.bwa_mem.bam resources/processed_data/ce11/NGS/HiC/bam/hpl2-lin61-old_rep2_2.bwa_mem.bam --binSize 1000 --minMappingQuality 20 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_rep2.bwa_mem.1kb.h5 --QCfolder resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_rep2.bwa_mem.1kb_QC --threads 1 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_rep2.bwa_mem1kb.hicBuildMatrix.log
hicBuildMatrix --inputBufferSize 200000 --restrictionSequence GATC --restrictionCutFile resources/processed_data/ce11/genomics/bed/hicFindRestSite/GATC.bed --danglingSequence GATC --maxLibraryInsertSize 700 --samFiles resources/processed_data/ce11/NGS/HiC/bam/N2-old_rep1_1.bwa_mem.bam resources/processed_data/ce11/NGS/HiC/bam/N2-old_rep1_2.bwa_mem.bam --binSize 1000 --minMappingQuality 20 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_rep1.bwa_mem.1kb.h5 --QCfolder resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_rep1.bwa_mem.1kb_QC --threads 1 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_rep1.bwa_mem1kb.hicBuildMatrix.log
hicBuildMatrix --inputBufferSize 200000 --restrictionSequence GATC --restrictionCutFile resources/processed_data/ce11/genomics/bed/hicFindRestSite/GATC.bed --danglingSequence GATC --maxLibraryInsertSize 700 --samFiles resources/processed_data/ce11/NGS/HiC/bam/I158A-old_rep1_1.bwa_mem.bam resources/processed_data/ce11/NGS/HiC/bam/I158A-old_rep1_2.bwa_mem.bam --binSize 1000 --minMappingQuality 20 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_rep1.bwa_mem.1kb.h5 --QCfolder resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_rep1.bwa_mem.1kb_QC --threads 1 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_rep1.bwa_mem1kb.hicBuildMatrix.log
hicBuildMatrix --inputBufferSize 200000 --restrictionSequence GATC --restrictionCutFile resources/processed_data/ce11/genomics/bed/hicFindRestSite/GATC.bed --danglingSequence GATC --maxLibraryInsertSize 700 --samFiles resources/processed_data/ce11/NGS/HiC/bam/met2-set25-set32-old_rep1_1.bwa_mem.bam resources/processed_data/ce11/NGS/HiC/bam/met2-set25-set32-old_rep1_2.bwa_mem.bam --binSize 1000 --minMappingQuality 20 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_rep1.bwa_mem.1kb.h5 --QCfolder resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_rep1.bwa_mem.1kb_QC --threads 1 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_rep1.bwa_mem1kb.hicBuildMatrix.log
hicSumMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_rep1.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.1kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old.bwa_mem.1kb.merge_rep.log
hicSumMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_rep1.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.1kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old.bwa_mem.1kb.merge_rep.log
hicSumMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_rep1.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.1kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old.bwa_mem.1kb.merge_rep.log
hicSumMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_rep1.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.1kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old.bwa_mem.1kb.merge_rep.log
hicSumMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_rep1.bwa_mem.1kb.h5 resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_rep2.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.1kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old.bwa_mem.1kb.merge_rep.log
hicSumMatrices --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_rep1.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.1kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old.bwa_mem.1kb.merge_rep.log
hicMergeMatrixBins --numBins 25 --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.1kb_to_25kb.hicSumdMatrices.log
hicMergeMatrixBins --numBins 25 --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.1kb_to_25kb.hicSumdMatrices.log
hicMergeMatrixBins --numBins 25 --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.1kb_to_25kb.hicSumdMatrices.log
hicMergeMatrixBins --numBins 25 --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.1kb_to_25kb.hicSumdMatrices.log
hicMergeMatrixBins --numBins 25 --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.1kb_to_25kb.hicSumdMatrices.log
hicMergeMatrixBins --numBins 25 --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.1kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.1kb_to_25kb.hicSumdMatrices.log
hicAdjustMatrix --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.masked.h5 --regions /nfs/work/gen2i/technique/bdd/bioDB/ce11/blacklisted_regions/ce11-blacklist.v2.bed --action mask 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.mask.log
hicAdjustMatrix --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.masked.h5 --regions /nfs/work/gen2i/technique/bdd/bioDB/ce11/blacklisted_regions/ce11-blacklist.v2.bed --action mask 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.mask.log
hicAdjustMatrix --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.masked.h5 --regions /nfs/work/gen2i/technique/bdd/bioDB/ce11/blacklisted_regions/ce11-blacklist.v2.bed --action mask 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.mask.log
hicAdjustMatrix --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.masked.h5 --regions /nfs/work/gen2i/technique/bdd/bioDB/ce11/blacklisted_regions/ce11-blacklist.v2.bed --action mask 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.mask.log
hicAdjustMatrix --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.masked.h5 --regions /nfs/work/gen2i/technique/bdd/bioDB/ce11/blacklisted_regions/ce11-blacklist.v2.bed --action mask 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.mask.log
hicAdjustMatrix --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.h5 --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.masked.h5 --regions /nfs/work/gen2i/technique/bdd/bioDB/ce11/blacklisted_regions/ce11-blacklist.v2.bed --action mask 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.mask.log
hicNormalize --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.masked.h5 --normalize norm_range --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.norm.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.norm.log 
hicNormalize --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.masked.h5 --normalize norm_range --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.norm.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.norm.log 
hicNormalize --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.masked.h5 --normalize norm_range --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.norm.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.norm.log 
hicNormalize --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.masked.h5 --normalize norm_range --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.norm.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.norm.log 
hicNormalize --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.masked.h5 --normalize norm_range --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.log 
hicNormalize --matrices resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.masked.h5 --normalize norm_range --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.norm.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.norm.log 
hicCorrectMatrix correct --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.h5 --correctionMethod KR --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.KR.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.KR.log
hicCorrectMatrix correct --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.norm.h5 --correctionMethod KR --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.norm.KR.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.norm.KR.log
hicCorrectMatrix correct --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.norm.h5 --correctionMethod KR --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.norm.KR.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.norm.KR.log
hicCorrectMatrix correct --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.norm.h5 --correctionMethod KR --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.norm.KR.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.norm.KR.log
hicCorrectMatrix correct --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.norm.h5 --correctionMethod KR --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.norm.KR.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.norm.KR.log
hicCorrectMatrix correct --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.norm.h5 --correctionMethod KR --outFileName resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.norm.KR.h5 2> resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.norm.KR.log
hicPCA --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-lin61-old_merged.bwa_mem.25kb.norm.KR.h5 --outputFileName resources/processed_data/ce11/NGS/HiC/hicPCA/hpl2-lin61-old_merged.bwa_mem.25kb.pca1.bw resources/processed_data/ce11/NGS/HiC/hicPCA/hpl2-lin61-old_merged.bwa_mem.25kb.pca2.bw --whichEigenvectors 1 2 --format bigwig --method lieberman --ignoreMaskedBins  --pearsonMatrix resources/processed_data/ce11/NGS/HiC/hicPCA/hpl2-lin61-old_merged.bwa_mem.25kb.pearson.h5 --extraTrack resources/processed_data/ce11/NGS/ChIPseq/bigwig/H3K9me3_N2_merged.bwa_aln.rmdup.bamCoverage.bw --histonMarkType inactive 2> resources/processed_data/ce11/NGS/HiC/hicPCA/hpl2-lin61-old_merged.bwa_mem.25kb.hicPCA.log
hicPCA --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/met2-set25-set32-old_merged.bwa_mem.25kb.norm.KR.h5 --outputFileName resources/processed_data/ce11/NGS/HiC/hicPCA/met2-set25-set32-old_merged.bwa_mem.25kb.pca1.bw resources/processed_data/ce11/NGS/HiC/hicPCA/met2-set25-set32-old_merged.bwa_mem.25kb.pca2.bw --whichEigenvectors 1 2 --format bigwig --method lieberman --ignoreMaskedBins  --pearsonMatrix resources/processed_data/ce11/NGS/HiC/hicPCA/met2-set25-set32-old_merged.bwa_mem.25kb.pearson.h5 --extraTrack resources/processed_data/ce11/NGS/ChIPseq/bigwig/H3K9me3_N2_merged.bwa_aln.rmdup.bamCoverage.bw --histonMarkType inactive 2> resources/processed_data/ce11/NGS/HiC/hicPCA/met2-set25-set32-old_merged.bwa_mem.25kb.hicPCA.log
hicPCA --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/N2-old_merged.bwa_mem.25kb.norm.KR.h5 --outputFileName resources/processed_data/ce11/NGS/HiC/hicPCA/N2-old_merged.bwa_mem.25kb.pca1.bw resources/processed_data/ce11/NGS/HiC/hicPCA/N2-old_merged.bwa_mem.25kb.pca2.bw --whichEigenvectors 1 2 --format bigwig --method lieberman --ignoreMaskedBins  --pearsonMatrix resources/processed_data/ce11/NGS/HiC/hicPCA/N2-old_merged.bwa_mem.25kb.pearson.h5 --extraTrack resources/processed_data/ce11/NGS/ChIPseq/bigwig/H3K9me3_N2_merged.bwa_aln.rmdup.bamCoverage.bw --histonMarkType inactive 2> resources/processed_data/ce11/NGS/HiC/hicPCA/N2-old_merged.bwa_mem.25kb.hicPCA.log
hicPCA --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/hpl2-old_merged.bwa_mem.25kb.norm.KR.h5 --outputFileName resources/processed_data/ce11/NGS/HiC/hicPCA/hpl2-old_merged.bwa_mem.25kb.pca1.bw resources/processed_data/ce11/NGS/HiC/hicPCA/hpl2-old_merged.bwa_mem.25kb.pca2.bw --whichEigenvectors 1 2 --format bigwig --method lieberman --ignoreMaskedBins  --pearsonMatrix resources/processed_data/ce11/NGS/HiC/hicPCA/hpl2-old_merged.bwa_mem.25kb.pearson.h5 --extraTrack resources/processed_data/ce11/NGS/ChIPseq/bigwig/H3K9me3_N2_merged.bwa_aln.rmdup.bamCoverage.bw --histonMarkType inactive 2> resources/processed_data/ce11/NGS/HiC/hicPCA/hpl2-old_merged.bwa_mem.25kb.hicPCA.log
hicPCA --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/I158A-old_merged.bwa_mem.25kb.norm.KR.h5 --outputFileName resources/processed_data/ce11/NGS/HiC/hicPCA/I158A-old_merged.bwa_mem.25kb.pca1.bw resources/processed_data/ce11/NGS/HiC/hicPCA/I158A-old_merged.bwa_mem.25kb.pca2.bw --whichEigenvectors 1 2 --format bigwig --method lieberman --ignoreMaskedBins  --pearsonMatrix resources/processed_data/ce11/NGS/HiC/hicPCA/I158A-old_merged.bwa_mem.25kb.pearson.h5 --extraTrack resources/processed_data/ce11/NGS/ChIPseq/bigwig/H3K9me3_N2_merged.bwa_aln.rmdup.bamCoverage.bw --histonMarkType inactive 2> resources/processed_data/ce11/NGS/HiC/hicPCA/I158A-old_merged.bwa_mem.25kb.hicPCA.log
hicPCA --matrix resources/processed_data/ce11/NGS/HiC/contactMatrix/lin61-old_merged.bwa_mem.25kb.norm.KR.h5 --outputFileName resources/processed_data/ce11/NGS/HiC/hicPCA/lin61-old_merged.bwa_mem.25kb.pca1.bw resources/processed_data/ce11/NGS/HiC/hicPCA/lin61-old_merged.bwa_mem.25kb.pca2.bw --whichEigenvectors 1 2 --format bigwig --method lieberman --ignoreMaskedBins  --pearsonMatrix resources/processed_data/ce11/NGS/HiC/hicPCA/lin61-old_merged.bwa_mem.25kb.pearson.h5 --extraTrack resources/processed_data/ce11/NGS/ChIPseq/bigwig/H3K9me3_N2_merged.bwa_aln.rmdup.bamCoverage.bw --histonMarkType inactive 2> resources/processed_data/ce11/NGS/HiC/hicPCA/lin61-old_merged.bwa_mem.25kb.hicPCA.log
