samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/hpl2a_rep1.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/hpl2a_rep1.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/I158A_rep2.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/I158A_rep2.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/met2-set25-set32_rep1.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/met2-set25-set32_rep1.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/N2_rep1.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/N2_rep1.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/hpl2a_rep2.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/hpl2a_rep2.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/lin61_rep1.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/lin61_rep1.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/met2-set25-set32_rep2.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/met2-set25-set32_rep2.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/N2_rep2.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/N2_rep2.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/lin61_rep2.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/lin61_rep2.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/hpl2bc_rep1.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/hpl2bc_rep1.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/hpl2_rep1.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/hpl2_rep1.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/hpl2-lin61_rep1.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/hpl2-lin61_rep1.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/hpl2bc_rep2.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/hpl2bc_rep2.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/hpl2_rep2.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/hpl2_rep2.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/hpl2-lin61_rep2.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/hpl2-lin61_rep2.STAR.sort.bam.bai
samtools index  resources/processed_data/ce11/NGS/RNAseq/bam/I158A_rep1.STAR.sort.bam resources/processed_data/ce11/NGS/RNAseq/bam/I158A_rep1.STAR.sort.bam.bai
